### ISSUE TITLE
Misleading information in https://thorntail.io/posts/announcing-thorntail-2-5-0-final/

### ISSUE THREAD

**Issue by openscript** [thorntail/thorntail.io#10]
Hello everybody

There is misleading information about the jwt microprofile within:
https://thorntail.io/posts/announcing-thorntail-2-5-0-final/

> The @LoginConfig annotation is no longer required, if the thorntail.microprofile.jwt.token.realm configuration property is set. If you use the annotation anyway, then make sure its realmName property is set to the same value as the thorntail.microprofile.jwt.token.realm configuration property.

It shouldn't be `thorntail.microprofile.jwt.token.realm` but instead `thorntail.microprofile.jwt.realm`.

e.g.:

```
thorntail:
  microprofile:
    jwt:
      realm: auth-domain
      token:
        issuedBy: "ch.obin.r.auth"
      roles:
        file: jwt-roles.properties
```

The documentation is correct though: https://docs.thorntail.io/2.5.0.Final/#_microprofile_jwt_rbac_auth
